# strings.out: strings.cpp
# 	g++ -g -O0 -std=c++17 -Wall strings.cpp -o strings.out

cpp_strings.out: cpp_strings.cpp
	g++ -g -O0 -std=c++17 -Wall cpp_strings.cpp -o cpp_strings.out


x:
	make -s
	make -s run

run:
	./cpp_strings.out

clean:
	rm *.out